executor: cluster-generic
cluster-generic-submit-cmd:
  sbatch
    --partition=batch
    --account=cedar_amlrecovery
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --gres={resources.gres}
    --job-name=smk-{rule}-{wildcards}
    --output=test_logs/20250822/{rule}/{rule}-{wildcards}-%j.out
    --parsable
    --time={resources.time}
default-resources:
  - time="01:00:00"
  - mem_mb=5000
  - gres="disk:1024"
jobs: 40
rerun-incomplete: True
use-conda: True

